=== hujungoo/blacklist/src/cfg/etc/schema/codetable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.brilliance.com.cn/codetable" targetNamespace="http://www.brilliance.com.cn/codetable" elementFormDefault="qualified">
	<xs:element name="codetables">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="codetable" type="codetableTyp" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="codetableTyp">
		<xs:sequence>
			<xs:element name="code" type="codeTyp" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="nonEmptyTyp" use="required" />
		<xs:attribute name="sql" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="codeTyp">
		<xs:attribute name="id" type="nonEmptyTyp" use="required" />
		<xs:attribute name="value" type="xs:string" />
	</xs:complexType>
	<xs:simpleType name="nonEmptyTyp">
		<xs:restriction base="xs:string">
			<xs:pattern value="(\s*\S+\s*)+" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== hujungoo/blacklist/src/cfg/etc/codetables.xml
<?xml version="1.0" encoding="UTF-8"?>
<codetables xmlns="http://www.brilliance.com.cn/codetable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.brilliance.com.cn/codetable schema/codetable.xsd">
    
    <codetable id="gender">
        <code id="M" value="男" />
        <code id="F" value="女" />
    </codetable>
    <codetable id="currency">
        <code id="001" value="CNY" />
        <code id="002" value="USD" />
        <code id="003" value="EUR" />
        <code id="004" value="HKD" />
        <code id="005" value="GBP" />
        <code id="006" value="JPY" />
        <code id="007" value="KRW" />
        <code id="008" value="CAD" />
        <code id="009" value="AUD" />
    </codetable>

    <codetable id="shotType2LimitName">
        <code id="NAME" value="namelimit"/>
        <code id="ADDRESS" value="addrlimit"/>
        <code id="COUNTRY" value="cnylimit"/>
        <code id="IDNUM" value="idnumlimit"/>
        <code id="DATE" value="datelimit"/>
        <code id="ROLE" value="rolelimit"/>
    </codetable>

</codetables>
